function [t_univ, FR_ideal, FR_from_Z, Z] = ...
    igualar_long(t_ideal, FR_ideal, time_mid, FR_from_Z, Z)

    N = min([ ...
        length(t_ideal), ...
        length(FR_ideal), ...
        length(time_mid), ...
        length(FR_from_Z), ...
        length(Z)]);

    % reescribimos los vectores con igual longitud

    t_univ = t_ideal(1:N); % vector t universal
    FR_ideal = FR_ideal(1:N);
    FR_from_Z = FR_from_Z(1:N);
    Z = Z(1:N);

end