function generarModo()

        modo = round(ModoField.Value);
        Ts = TsField.Value;

        if Ts <= 0

            uialert(fig,...
                'Ts debe ser positivo.',...
                'Error');

            return
        end

        %% Obtener duración del modo

        t_final = obtenerDuracionModo(modo);

        %% Generar vector temporal

        t = (0:Ts:t_final)';

        %% Generar modo

        [FR,...
            FRp,...
            FRm] = modo_ideal(modo,t);

        %% Información

        texto = sprintf([...
            'Modo: R%d\n\n' ...
            'Duración total: %.1f s\n\n' ...
            'Número de muestras: %d\n\n' ...
            'FR mínimo: %.2f µL/min\n\n' ...
            'FR máximo: %.2f µL/min'],...
            modo,...
            t_final,...
            length(t),...
            min(FR),...
            max(FR));

        infoLabel.Value = texto;

        %% Plot

        cla(ax)

        hold(ax,'on')

        plot(ax,...
            t,...
            FR,...
            'k',...
            'LineWidth',2,...
            'DisplayName','Ideal');

        plot(ax,...
            t,...
            FRp,...
            '--g',...
            'LineWidth',1.5,...
            'DisplayName','+10%');

        plot(ax,...
            t,...
            FRm,...
            '--r',...
            'LineWidth',1.5,...
            'DisplayName','-10%');

        hold(ax,'off')

        legend(ax,'show')

        ylim(ax,[0 max(FRp)*1.2])

        %% Exportar al Workspace

        assignin('base','t_ideal',t); % vector tiempo ideal

        assignin('base','FR_ideal',FR); % vector modo FR ideal

        assignin('base','FR_plus10',FRp); % vector modo FR ideal +10%

        assignin('base','FR_minus10',FRm); % vector modo FR ideal -10%

        assignin('base','modo_ID',modo); % id del modo

    end
