function texto = generarManualCompleto()

        texto = sprintf([ ...
            '====================================================\n' ...
            'MANUAL DE MODOS DE FLOW RATE\n' ...
            '====================================================\n\n' ...
            'Los modos R1-R93 representan diferentes perfiles\n' ...
            'temporales de caudal utilizados para evaluar la\n' ...
            'respuesta dinámica del sensor microfluídico.\n\n' ...
            'Cada modo está compuesto por una combinación de:\n\n' ...
            '• Tramos estacionarios (caudal constante)\n' ...
            '• Rampas lineales ascendentes\n' ...
            '• Rampas lineales descendentes\n\n' ...
            'Las duraciones y amplitudes de cada transición\n' ...
            'se detallan a continuación.\n\n' ...
            '====================================================\n\n']);

        modos = [1 2 3 4 5 6 7 8 91 92 93];

        for m = modos

            [t_puntos, flow_puntos] = obtenerDefinicionModo(m);

            texto = [texto sprintf('Modo R%d\n',m)];
            texto = [texto sprintf('----------------------------------------------------\n')];

            contador = 1;

            for k = 1:length(flow_puntos)-1

                duracion = t_puntos(k+1)-t_puntos(k);

                if abs(flow_puntos(k+1)-flow_puntos(k)) < 1e-9

                    texto = [texto sprintf( ...
                        'Tramo %d: %.2f µL/min durante %.0f s\n', ...
                        contador,...
                        flow_puntos(k),...
                        duracion)];

                else

                    texto = [texto sprintf( ...
                        'Rampa %d: %.2f → %.2f µL/min en %.0f s\n', ...
                        contador,...
                        flow_puntos(k),...
                        flow_puntos(k+1),...
                        duracion)];

                end

                contador = contador + 1;

            end

            texto = [texto sprintf('\nDuración total: %.0f s\n\n',t_puntos(end))];

            texto = [texto sprintf( ...
                '====================================================\n\n')];

        end

    end
